---

- hosts: pi
  become: yes
  vars_files:
    - vars.yml
  pre_tasks:
    - include_tasks: pre_tasks/apt_repo_set.yml
      when: ansible_os_family == 'Debian'
    - import_tasks: pre_tasks/create_users_dir.yml
  tasks:
    - import_tasks: tasks/configure_prometheus.yml
    - import_tasks: tasks/configure_grafana.yml
  handlers:
    - name: start services
      service:
        name: "{{ item }}"
        daemon_reload: yes
        enabled: yes
        state: started
      loop:
        - prometheus
        - grafana-server
